### ISSUE TITLE
✨ feat: Impl Recording page

### ISSUE THREAD

**Issue by maiload** [KakaoTech-14-All-in-one-move/AIM-14-FE#11]
# Title

- 화면(음성) 녹화 페이지 구현

# TODO

- [x] 화면 녹화 박스 구현
- [x] 음성 녹음 박스 구현
- [x] 화면 공유 박스 구현
- [x] 파일 업로드 박스 구현
- [x] 녹화(녹음), 카메라 on/off, 화면 공유, 녹화(녹음) 다운로드, Ai Feedback 버튼 구현
- [x] 화면 확대 기능 및 팝업 기능 구현

# etc
