### ISSUE TITLE
✨ feat: Implement server backend logic

### ISSUE THREAD

**Issue by KmYgJn** [KakaoTech-14-All-in-one-move/AIM-14-FE#25]
# Title

- 서버와 관련한 로직 추가

# TODO

- [x] 서버 추가 
- [x] 서버 삭제
- [x] 서버에 유저 초대
- [x] 서버 이름 변경
- [x] 서버 이미지 변경

# etc

- 어쩌구저쩌구
