### ISSUE TITLE
🐛 fix: bug

### ISSUE THREAD

**Issue by KmYgJn** [KakaoTech-14-All-in-one-move/AIM-14-FE#46]
# Title

- 버그 수정

# TODO

- [ ] 클라이언트 서버, 채널 동기화
- [x] 서버 생성 시 기본 채팅, 음성, 화상 채널 1개씩 있도록 수정 (너무 복잡해지는 관계로 X)
- [x] 채팅에서 다른 클라이언트의 profile image 가져오도록 수정
- [x] 홈 화면 (헤더 포함)
- [x] 로그아웃 시 login, home 화면이 계속 뒤바뀌는 에러 (회원탈퇴 때도 그러는지 확인해 봐야함)
- [x] 로그인 할 때, 가끔 바로 화면 안나올 때 있음
- [ ] OAuth2 Prod 환경에서도 되도록 (테스트)

# etc

- 흐읍
